repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/prettier/prettier
    rev: "2.0.5"
    hooks:
      - id: prettier
