language: node_js
node_js:
  - 12

branches:
  only:
    - master

install:
  - npm install -g @angular/cli

script:
  - npm i
  - ng build --prod
  - echo "cristianaldea.online" > dist/project-megaphone/CNAME

deploy:
  provider: pages
  local_dir: dist/project-megaphone/
  github_token: $GITHUB_TOKEN
  repo: TheGreatMarkus/TheGreatMarkus.github.io
  target_branch: master
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
