language: node_js
node_js:
  - 12

branches:
  only:
    - master

install:
  - npm install -g @angular/cli

script:
  - npm i
  - ng build --prod

deploy:
  provider: firebase
  on:
    branch: master
  token: $FIREBASE_TOKEN
  edge: true
